import { randomInt } from "node:crypto";

export const EXAMPLE_PROMPTS = [
  "Un pingüino atendiendo una panadería",
  "Una abuela ganando una carrera de motos",
  "Un dinosaurio tomando mate en la playa",
  "Un gato astronauta arreglando un satélite",
  "Una jirafa escondida dentro de un ascensor",
  "Un fantasma haciendo una videollamada",
  "Un pulpo tocando la batería",
  "Una vaca practicando paracaidismo",
  "Un robot cocinando empanadas",
  "Un perro manejando un taxi bajo la lluvia",
  "Una llama cantando en un karaoke",
  "Un tiburón comprando verduras",
  "Un caracol llegando tarde a una boda",
  "Una gallina investigando un crimen",
  "Un oso polar vendiendo helados",
  "Un extraterrestre aprendiendo a bailar tango",
  "Una sirena esperando el ómnibus",
  "Un dragón apagando las velas de su cumpleaños",
  "Un mono sacándose una foto en la Luna",
  "Una oveja cortándole el pelo a un peluquero",
  "Un mago que perdió su conejo",
  "Una momia tomando sol en una reposera",
  "Un pirata buscando señal de wifi",
  "Una bruja atrapada en un embotellamiento",
  "Un vampiro cepillándose los dientes",
  "Un superhéroe paseando un caniche",
  "Un caballero medieval usando una computadora",
  "Una princesa arreglando una cañería",
  "Un ninja preparando panqueques",
  "Un vikingo haciendo yoga",
  "Una tostadora escapando de la cocina",
  "Una heladera de vacaciones en el Caribe",
  "Un paraguas que le teme a la lluvia",
  "Una bicicleta estacionada arriba de un árbol",
  "Un despertador durmiendo una siesta",
  "Una lámpara buscando el interruptor",
  "Un sillón navegando por el océano",
  "Una cafetera dirigiendo una reunión",
  "Un lavarropas bailando salsa",
  "Una valija que se niega a viajar",
  "Una pizza entregando a su repartidor",
  "Un choripán vestido de gala",
  "Una milanesa jugando al tenis",
  "Un mate gigante en medio de la ciudad",
  "Una medialuna haciendo pesas",
  "Un helado derritiendo al Sol",
  "Una banana hablando por teléfono",
  "Una cebolla contando un chiste triste",
  "Un tomate huyendo de una ensalada",
  "Una torta de cumpleaños apagando personas",
  "Un castillo inflable volando sobre las montañas",
  "Una montaña rusa atravesando una oficina",
  "Un faro perdido en el desierto",
  "Una isla flotando sobre las nubes",
  "Un volcán lleno de pochoclo",
  "Una nube regando una sola flor",
  "La Luna pescando estrellas",
  "El Sol usando anteojos oscuros",
  "Un arcoíris pintado de blanco y negro",
  "Un tornado ordenando una habitación",
  "Una banda de pingüinos robando un banco",
  "Dos esqueletos jugando al ajedrez",
  "Tres ratones construyendo un cohete",
  "Una familia de patos perdida en un shopping",
  "Un ejército de hormigas llevando una sandía",
  "Una reunión de gatos en un tejado",
  "Dos peces discutiendo dentro de una pecera",
  "Un grupo de zombis esperando al dentista",
  "Una orquesta dirigida por un mosquito",
  "Un equipo de fútbol formado por robots",
  "Un detective siguiendo las huellas de una gallina",
  "Un científico inventando una máquina de hacer siestas",
  "Un chef cocinando sobre un volcán",
  "Un fotógrafo persiguiendo al monstruo del lago",
  "Un jardinero plantando árboles de chocolate",
  "Un bombero apagando una vela diminuta",
  "Un astronauta olvidando el casco en casa",
  "Un arqueólogo encontrando un control remoto",
  "Un músico tocando una guitarra invisible",
  "Un árbitro expulsando a la pelota",
  "Un casamiento en el fondo del mar",
  "Una fiesta de cumpleaños dentro de un submarino",
  "Un asado en la cima de una montaña",
  "Una carrera de caracoles con público impaciente",
  "Un picnic invadido por dinosaurios",
  "Una clase de natación para fantasmas",
  "Un partido de tenis en el espacio",
  "Una entrevista de trabajo para superhéroes",
  "Un recital silencioso en una biblioteca",
  "Una tormenta dentro de una taza de café",
  "Un auto con patas cruzando un río",
  "Un barco navegando por una avenida",
  "Un avión estacionado en un balcón",
  "Un tren persiguiendo su último vagón",
  "Un cohete frenando en un semáforo",
  "Una moto conducida por un pez",
  "Un colectivo lleno de animales de granja",
  "Un globo aerostático atrapado en una telaraña",
  "Un triciclo compitiendo en una carrera de Fórmula 1",
  "Un ovni llevándose una estatua de la plaza",
] as const;

export function randomExamplePrompt(
  selectIndex: (maximum: number) => number = randomInt,
): string {
  return EXAMPLE_PROMPTS[selectIndex(EXAMPLE_PROMPTS.length)] ?? EXAMPLE_PROMPTS[0];
}
